name: Activate Unity License

on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request Unity License File
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Activation File
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.22f1

      - name: Expose as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.22f1.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
